#!/usr/bin/env node

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const target = process.argv[2];
if (!target) {
  console.log('missing <target>');
  process.exit(0);
}

const makeHash = file => {
  let content = fs.readFileSync(
    path.join(path.resolve(target, '..'), file)
  );
  return crypto.createHash('md5')
    .update(content)
    .digest('hex')
}

const makeReg = file => (
  new RegExp(`"(${file}\\?)(\\w+)"`, 'g')
);

const matches = [
  'style.css',
  'lib/css-doodle.min.js',
  'main.js'
];

try {
  let content = fs.readFileSync(target, 'utf8');
  matches.forEach(m => {
    content = content.replace(
      makeReg(m), (_, n) => `"${n + makeHash(m)}"`
    );
  });
  if (content) {
    fs.writeFileSync(target, content, 'utf8');
  }
} catch (e) {
  // it's ok
}
