#!/usr/bin/env node

const fs = require('fs');
const path = require('path');

const target = process.argv[2];
if (!target) {
  console.log('missing <target>');
  process.exit(0);
}

try {
  let content = fs.readFileSync(target, 'utf8');
  if (content) {
    content = content.replace(/\t/g, '  ');
    fs.writeFileSync(target, content, 'utf8');
  }
} catch (e) {
  // it's ok
}
